### ISSUE TITLE
I/O Processes

### ISSUE THREAD

**Issue by tjsg1992** [tjsg1992/422-Final-Project#1]
> You already have these processes. In the final simulation though you should limit the number of these in the mix to no more than 50 - with dynamic creation and termination as before.

1. ~~Bring over the code to dynamically create PCBs from Project03.~~
2. ~~Limit the number of PCBs created to 50.~~
3. ~~Create a trace for when a PCB is created.~~

4. We still need to be simulating I/O PCBs to almost the extent that we did in Project03, so we need to import more code from Project03's scheduler code (see the /ref/ folder), including integrate iodevice.c, context-switching, etc.
5. Create new I/O PCBs during context switching.

**Comment by tjsg1992** [comment]
Created an enum for process types.
create_pcb() now accepts a process type, and makes a PCB accordingly.
create_pcb() creates I/O PCBs like before, except it now generates the priority weighted randomly. If it is a CI PCB, then its priority is set to 0.
10 I/O PCBs are now created before the main loop starts, with creation messages printing to the console.

**Comment by VRushLP** [comment]
I moved over some of the logic from project 3. It can be found in the cpu_cycle() function.
A lot of it is comments, since I wasn't sure how much 'almost the extent' was.
Notably, it's missing both the scheduler and ISR functions.

**Comment by tjsg1992** [comment]
Working on wrapping this up now.
