### ISSUE TITLE
Back to Priority Scheduling

### ISSUE THREAD

**Issue by tjsg1992** [tjsg1992/422-Final-Project#2]
> For this last simulation you will go back to using the priority queue for the ready queue but not for the I/O or synchronization waiting queues. This time create four priority levels and populate the levels roughly with the following percentages: 0 - 5%, 1 - 80%, 2 - 10%, 3 - 5%. In your dynamic creation and termination algorithms (when you fill the new process list and empty the terminated process list) you can keep a running record of how may of each priority are currently in the running mix. Of the 5% priority 0 processes they should all be compute intensive types (next).

> You will need to implement a starvation prevention mechanism that detects when lower level priority processes are not getting CPU time and you temporarily boost their priority to the next higher level for a quantum. This means you will need to modify the PCB to include a flag for such a boost and keep count of the quanta so that your algorithm can demote the process back to its original priority level. This will be a test of your thinking and design skills.

> In addition to the report on performance, include a summary of your starvation prevention algorithm and implementation techniques so I can see how you solved the problem.

NOTE:
Priority 0 is the highest priority.

1. ~~Bring over the priority_queue code from Project01.~~
2. ~~Implement a priority queue in scheduler for the ready queue.~~
3. ~~Set the priority queue so that it only contains four priority levels.~~
4. ~~Upon PCB creation, give it a priority. Follow the percentages either with a random number algorithm or by looking at pre-existing processes. Only compute intensive processes should be set to priority 0.~~
5. ~~Add a boost flag for aging. The boost flag is an integer that contains the number of priority levels that the PCB has been promoted. PCBs can be boosted into Priority 0, but they shouldn't need to be.~~
6. Add a summary for the starvation prevention algorithm we came up with.
7. ~~PCBs should be demoted to its original priority after being dequeued.~~
8. ~~Every x cycles, iterate over every ready queue, check if a PCB has not been run for y cycles, and if so, promote it.~~

**Comment by tjsg1992** [comment]
priority_queue has been modified to compile with our most recent version of queue.

**Comment by VRushLP** [comment]
3, 4 and 5 appear to be done.

**Comment by tjsg1992** [comment]
All that is left on this issue is the summary.

**Comment by VRushLP** [comment]
6 is handled both as a fair amount of comments in the actual function and a separate .txt file.
Both can be found in the 'starving' branch.

**Comment by tjsg1992** [comment]
Gracias!
