### ISSUE TITLE
Implementing Synchronization Services

### ISSUE THREAD

**Issue by tjsg1992** [tjsg1992/422-Final-Project#4]
> You will be simulating synchronization services in order to implement coordination between various processes. Specifically you will implement mutexes and condition variables based on the pthread versions (as in the book). For those of you who are writing pthreaded programs DO NOT USE THE PTHREAD FUNCTIONS. Everyone is supposed to simulate these functions.

> Each synchronization tool will be built using a pointer variable to the process that currently "owns" the mechanism. For example a mutex struct would contain a pointer variable to the process that has a lock on the mutex. The struct will also contain a FIFO-Queue to hold process pointers that are currently blocked awaiting getting a lock.

> You will need to build several more arrays (like the I/O arrays) into the kinds of processes (below) that will be using synchronization tools. These arrays will contain the step numbers when these processes execute traps to lock, or trylock, or unlock a mutex. They will also contain steps when processes wait or signal condition variables. The difference between these arrays and the I/O arrays is that these arrays will be hand-crafted to implement the appropriate situations as presented below. You will hard-code the values into the arrays but you must also alter your random generating algorithm for the I/O arrays to make sure none of the numbers recorded there interfere with these hand-crafted numbers, i.e. you don't want to trap to an I/O after locking a mutex!

1. Create a mutex struct that contains a pointer to the PCB that owns it, and a queue of pointers for those that are waiting for access.
2. Need to spend some time looking into part three of this.

**Comment by VRushLP** [comment]
Working on item 1 of this issue now.

**Comment by VRushLP** [comment]
Just pushed a fix to mutex in the aptly named 'mutex-fix' branch

**Comment by VRushLP** [comment]
Since we learned in class that MRU and IO PCBs are strictly different things, I think we can consider this issue closed.
