### ISSUE TITLE
Producer-Consumer Pairs

### ISSUE THREAD

**Issue by tjsg1992** [tjsg1992/422-Final-Project#5]
**TENTATIVELY FINISHED : DO NOT WORK ON THIS**

> You will need to set up some process pairs (no more than ten). In each pair one process will be a producer and the other will be a consumer. These processes are just like all the others except that they are created in pairs and have some additional functions to handle their special jobs.

> To allow the pair to communicate you will need a global integer that can be read from and written to by the pair. This variable needs to be protected in a critical region.

> The producer will increment a variable each time through its cycle. Use the solution to the producer-consumer problem as given in section 12.2.9 of the text (modified to only use a single integer global variable as the shared memory).

> In your traces you should see your producer process write the sequence of numbers (i.e. 1, 2, 3,...n) to the shared space and the consumer reading the sequence (and print to the trace to verify) in the same order. No duplicate or missed reading events should occur.

> I would recommend you label your producers and consumers (in pairs) with names and not just PIDs. That way you can more easily pick out paired operations.

1. Discuss if we want to create a new type of PCB or just include a flag and some functions with the pre-existing one.
2. Implement the creation of these functions, assigning one to be a consumer, the other to be a producer, and they should be named. Limited to 10 pairs.
3. We have multiple pairs each changing some global integer. Discuss if we want to use an array for this.
4. Implement the producer-consumer pair functions.
5. Add traces.

**TENTATIVELY FINISHED : DO NOT WORK ON THIS**

**Comment by cresse** [comment]
Working on this now.

**Comment by tjsg1992** [comment]
Assuming that my implementation is correct, this is complete. I'll leave it open for now until we talk it over in class and merge the branch.
